"""Generic single-database configuration."""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26d5dd441dbd'
down_revision = '46bf844acb96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 