"""Generic single-database configuration."""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46bf844acb96'
down_revision = '6cb8bc33e30c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 임시로 NOT NULL 제약조건 제거
    op.alter_column('trees', 'tag_number', nullable=True)
    
    # 숫자가 아닌 값을 0으로 설정 (NULL 대신)
    op.execute("UPDATE trees SET tag_number = '0' WHERE tag_number !~ '^[0-9]+$' OR tag_number IS NULL")
    
    # 정수형으로 변환
    op.execute("ALTER TABLE trees ALTER COLUMN tag_number TYPE integer USING (tag_number::integer)")
    
    # NOT NULL 제약조건 다시 추가
    op.alter_column('trees', 'tag_number', nullable=False)
    op.alter_column('trees', 'common_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trees', 'common_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('trees', 'tag_number',
               existing_type=sa.INTEGER(),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ### 