"""Add tree fields"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = '78ed79b76b66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create trees table first
    op.create_table('trees',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Add new columns in the order matching CSV
    op.add_column('trees', sa.Column('tag_number', sa.String(length=50), nullable=True))
    op.add_column('trees', sa.Column('common_name', sa.String(length=100), nullable=True))
    op.add_column('trees', sa.Column('species', sa.String(length=100), nullable=True))
    op.add_column('trees', sa.Column('location', Geometry('POINT', srid=4326), nullable=True))
    op.add_column('trees', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('trees', sa.Column('diameter', sa.Float(), nullable=True))
    op.add_column('trees', sa.Column('crown_height', sa.Float(), nullable=True))
    op.add_column('trees', sa.Column('crown_spread', sa.Float(), nullable=True))
    op.add_column('trees', sa.Column('contributors', sa.String(length=200), nullable=True))
    op.add_column('trees', sa.Column('last_inspection', sa.DateTime(), nullable=True))
    op.add_column('trees', sa.Column('health_condition', sa.String(length=50), nullable=True))
    op.add_column('trees', sa.Column('last_pruned', sa.DateTime(), nullable=True))
    op.add_column('trees', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trees')
    # ### end Alembic commands ### 